version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    networks:
      - backend
  influx:
    image: influxdb:latest
    container_name: "influx"
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=xrazis
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=razis
      - DOCKER_INFLUXDB_INIT_BUCKET=ichnaea
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
      - INFLUXDB_HTTP_FLUX_ENABLED
    volumes:
      - ./database/influx:/var/lib/influxdb2
      - ./database/influx:/etc/influxdb2
    networks:
      - backend
      - monitor
  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor
    depends_on:
      - influx
  mongo:
    image: mongo:latest
    container_name: "mongo"
    restart: always
    volumes:
      - ./database/mongo:/data/db
      - ./database/mongo:/data/configdb
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  backend:
    build: ./server
    container_name: "backend"
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    networks:
      - backend
      - frontend
    depends_on:
      - redis
      - influx
      - mongo
  frontend:
    build: ./web
    container_name: "frontend"
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/app/web
      - /usr/src/app/web/node_modules
    networks:
      - frontend
    depends_on:
      - backend
  test_client:
    build: ./client
    container_name: "test_client"
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    networks:
      - backend
    depends_on:
      - backend
networks:
  backend:
  frontend:
  monitor:
volumes:
  mongodb:
  influx: