version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    networks:
      - backend
  influx:
    image: influxdb:latest
    container_name: "influx"
    restart: always
    env_file:
      - influx-variables.env
    volumes:
      - ./database/influx:/var/lib/influxdb2
      - ./database/influx:/etc/influxdb2
    networks:
      - backend
      - monitor
  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor
    depends_on:
      - influx
  mongo:
    image: mongo:latest
    container_name: "mongo"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo:/data/db
      - ./database/mongo:/data/configdb
    networks:
      - backend
    env_file:
      - mongo-variables.env
  backend:
    build: ./server
    container_name: "backend"
    ports:
      - "8000:8000"
      - "9229:9229"
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    networks:
      - backend
      - frontend
    depends_on:
      - redis
      - influx
      - mongo
  frontend:
    build: ./web
    container_name: "frontend"
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/app/web
      - /usr/src/app/web/node_modules
    networks:
      - frontend
    depends_on:
      - backend
  client:
    build: ./client
    container_name: "client"
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
      - /run/udev:/run/udev:ro
      - /dev:/dev
    network_mode: "host"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
networks:
  backend:
  frontend:
  monitor:
volumes:
  mongodb:
  influx: