version: "3.9"
services:
  redis:
    image: "redis:alpine"
    networks:
      - backend
  influx:
    image: "influxdb:alpine"
    networks:
      - backend
    volumes:
      - /home/xrazis/Documents/random_code/database/influx/:/var/lib/influxdb
  backend:
    build: ""
    ports:
      - "6000:6000"
    networks:
      - backend
    depends_on:
      - redis
      - influx
networks:
  backend:
